name: Advanced dbt Multi-Environment Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install sqlfluff
      run: pip install sqlfluff
    - name: Lint SQL
      run: sqlfluff lint models/ --config .sqlfluff

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ci, staging]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache dbt packages
      uses: actions/cache@v3
      with:
        path: ~/.dbt
        key: ${{ runner.os }}-dbt-${{ hashFiles('**/packages.yml') }}
        
    - name: Install dependencies
      run: |
        pip install dbt-snowflake
        dbt deps
        
    - name: Run dbt build
      run: dbt build --target ${{ matrix.target }}
      env:
        DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
        DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
        DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
        DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
        DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
        DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
        DBT_SNOWFLAKE_SCHEMA: ${{ matrix.target }}_${{ github.run_id }}

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install dbt-snowflake
        dbt deps
        
    - name: Deploy to production
      run: dbt run --target prod
      env:
        DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
        DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
        DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
        DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
        DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE_PROD }}
        DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
        DBT_SNOWFLAKE_SCHEMA: prod